/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Controlador.Pensionado;
import Modelo.ConexionMySQL;

import javax.swing.*;
import java.awt.*;
import java.sql.Connection;


/**
 *
 * @author Erick
 */
public class frmlogin extends javax.swing.JDialog {

    ConexionMySQL con = new ConexionMySQL();
    
    Pensionado pensionado = new Pensionado();
    
    Connection cn = con.conectar();
    
    public static frmregistro frmRegistro;
    
    public frmlogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        FondoPanel = new javax.swing.JPanel();
        IniciarSesionPanel = new javax.swing.JPanel();
        IconLogin = new javax.swing.JLabel();
        TituloInicioSesion = new javax.swing.JLabel();
        PanelUser = new javax.swing.JPanel();
        UserField = new javax.swing.JTextField();
        LabelUser = new javax.swing.JLabel();
        PanelUser3 = new javax.swing.JPanel();
        LabelUser3 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        IngresarButton = new javax.swing.JButton();
        RegistroLinkPanel = new javax.swing.JPanel();
        RegistroButton = new javax.swing.JButton();
        PreguntaText = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Moonligth Parking - Iniciar Sesión");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        FondoPanel.setBackground(new java.awt.Color(255, 255, 255));

        IniciarSesionPanel.setBackground(new java.awt.Color(255, 255, 255));
        IniciarSesionPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 56, 112), 4, true));

        IconLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImgLogin.png"))); // NOI18N

        TituloInicioSesion.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        TituloInicioSesion.setForeground(new java.awt.Color(238, 56, 112));
        TituloInicioSesion.setText("Iniciar Sesión");

        PanelUser.setBackground(new java.awt.Color(238, 56, 112));
        PanelUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        UserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserFieldActionPerformed(evt);
            }
        });

        LabelUser.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        LabelUser.setForeground(new java.awt.Color(255, 255, 255));
        LabelUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelUser.setText("Usuario");

        javax.swing.GroupLayout PanelUserLayout = new javax.swing.GroupLayout(PanelUser);
        PanelUser.setLayout(PanelUserLayout);
        PanelUserLayout.setHorizontalGroup(
            PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUserLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LabelUser, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UserField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelUserLayout.setVerticalGroup(
            PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUserLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelUserLayout.createSequentialGroup()
                        .addComponent(LabelUser)
                        .addContainerGap())))
        );

        PanelUser3.setBackground(new java.awt.Color(238, 56, 112));
        PanelUser3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelUser3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        LabelUser3.setForeground(new java.awt.Color(255, 255, 255));
        LabelUser3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelUser3.setText("Contraseña");

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelUser3Layout = new javax.swing.GroupLayout(PanelUser3);
        PanelUser3.setLayout(PanelUser3Layout);
        PanelUser3Layout.setHorizontalGroup(
            PanelUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUser3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelUser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelUser3Layout.setVerticalGroup(
            PanelUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUser3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(PanelUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUser3Layout.createSequentialGroup()
                        .addComponent(LabelUser3)
                        .addContainerGap())
                    .addComponent(PasswordField)))
        );

        IngresarButton.setBackground(new java.awt.Color(238, 56, 112));
        IngresarButton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        IngresarButton.setForeground(new java.awt.Color(255, 255, 255));
        IngresarButton.setText("Ingresar");
        IngresarButton.setBorder(null);
        IngresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IniciarSesionPanelLayout = new javax.swing.GroupLayout(IniciarSesionPanel);
        IniciarSesionPanel.setLayout(IniciarSesionPanelLayout);
        IniciarSesionPanelLayout.setHorizontalGroup(
            IniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IniciarSesionPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(IniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(IniciarSesionPanelLayout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(TituloInicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(70, 70, 70))
                        .addGroup(IniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanelUser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(IniciarSesionPanelLayout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(IconLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(97, 97, 97)))
                    .addGroup(IniciarSesionPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(IngresarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );
        IniciarSesionPanelLayout.setVerticalGroup(
            IniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IniciarSesionPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(IconLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TituloInicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(PanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelUser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IngresarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        RegistroLinkPanel.setBackground(new java.awt.Color(255, 255, 255));
        RegistroLinkPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 56, 112), 4));

        RegistroButton.setBackground(new java.awt.Color(238, 56, 112));
        RegistroButton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        RegistroButton.setForeground(new java.awt.Color(255, 255, 255));
        RegistroButton.setText("Registrase");
        RegistroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroButtonActionPerformed(evt);
            }
        });

        PreguntaText.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        PreguntaText.setText("¿Aún no eres pensionado?");

        javax.swing.GroupLayout RegistroLinkPanelLayout = new javax.swing.GroupLayout(RegistroLinkPanel);
        RegistroLinkPanel.setLayout(RegistroLinkPanelLayout);
        RegistroLinkPanelLayout.setHorizontalGroup(
            RegistroLinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroLinkPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PreguntaText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(RegistroLinkPanelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(RegistroButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegistroLinkPanelLayout.setVerticalGroup(
            RegistroLinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroLinkPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(PreguntaText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegistroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FondoPanelLayout = new javax.swing.GroupLayout(FondoPanel);
        FondoPanel.setLayout(FondoPanelLayout);
        FondoPanelLayout.setHorizontalGroup(
            FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IniciarSesionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegistroLinkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        FondoPanelLayout.setVerticalGroup(
            FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(IniciarSesionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegistroLinkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void IngresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarButtonActionPerformed
        
        String user = UserField.getText();
        String contra = PasswordField.getText();
        
        if(user.isEmpty() || contra.isEmpty()){
            JOptionPane.showMessageDialog(null, "Rellena todos los campos, por favor.");
        }else{
            if(!pensionado.autentica(user, contra)){
                 JOptionPane.showMessageDialog(null, "Usuario y/o contrasena incorrectos.");
            }else{
                JOptionPane.showMessageDialog(null, "Inicio de sesión exitoso.");
                this.dispose();
                System.exit(0);
            }
        }
    }//GEN-LAST:event_IngresarButtonActionPerformed

    private void RegistroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroButtonActionPerformed
        frmRegistro = new frmregistro(null, true);
        frmRegistro.setVisible(true
        );
    }//GEN-LAST:event_RegistroButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmlogin dialog = new frmlogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPanel;
    private javax.swing.JLabel IconLogin;
    private javax.swing.JButton IngresarButton;
    private javax.swing.JPanel IniciarSesionPanel;
    private javax.swing.JLabel LabelUser;
    private javax.swing.JLabel LabelUser3;
    private javax.swing.JPanel PanelUser;
    private javax.swing.JPanel PanelUser3;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PreguntaText;
    private javax.swing.JButton RegistroButton;
    private javax.swing.JPanel RegistroLinkPanel;
    private javax.swing.JLabel TituloInicioSesion;
    private javax.swing.JTextField UserField;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/LogoMP.jpg")));
    }
}
