/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;
import Controlador.*;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Erick
 */
public class frmregistro extends javax.swing.JDialog {

    public static frmRegistroTarjeta frmRegistroT;
    
    Suscripcion scp = new Suscripcion();
    
    public frmregistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanel = new javax.swing.JPanel();
        RegistroPanel = new javax.swing.JPanel();
        TituloLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        NombreTextField = new javax.swing.JTextField();
        ApellidoPTextField = new javax.swing.JTextField();
        ApellidoMTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        UsuarioTextField = new javax.swing.JTextField();
        ContraseñaTextField = new javax.swing.JTextField();
        ConfirmarContraTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        ContinuarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Moonligth Parking - Registro");

        FondoPanel.setBackground(new java.awt.Color(255, 255, 255));

        RegistroPanel.setBackground(new java.awt.Color(255, 255, 255));
        RegistroPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 56, 112), 4, true));

        TituloLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        TituloLabel.setForeground(new java.awt.Color(238, 56, 112));
        TituloLabel.setText("Datos Personales");

        jSeparator2.setBackground(new java.awt.Color(238, 56, 112));
        jSeparator2.setForeground(new java.awt.Color(238, 56, 112));

        NombreTextField.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        NombreTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 56, 112), 1, true), "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 3, 18), new java.awt.Color(238, 56, 112))); // NOI18N

        ApellidoPTextField.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        ApellidoPTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 56, 112), 1, true), "Apellido Paterno ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 3, 18), new java.awt.Color(238, 56, 112))); // NOI18N
        ApellidoPTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoPTextFieldActionPerformed(evt);
            }
        });

        ApellidoMTextField.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        ApellidoMTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 56, 112), 1, true), "Apellido Materno ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 3, 18), new java.awt.Color(238, 56, 112))); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(238, 56, 112));
        jSeparator1.setForeground(new java.awt.Color(238, 56, 112));

        UsuarioTextField.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        UsuarioTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 56, 112), 1, true), "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 3, 18), new java.awt.Color(238, 56, 112))); // NOI18N

        ContraseñaTextField.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        ContraseñaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 56, 112), 1, true), "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 3, 18), new java.awt.Color(238, 56, 112))); // NOI18N

        ConfirmarContraTextField.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        ConfirmarContraTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 56, 112), 1, true), "Confirmar contraseña ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 3, 18), new java.awt.Color(238, 56, 112))); // NOI18N
        ConfirmarContraTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarContraTextFieldActionPerformed(evt);
            }
        });

        EmailTextField.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        EmailTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 56, 112), 1, true), "Email ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 3, 18), new java.awt.Color(238, 56, 112))); // NOI18N
        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });

        Telefono.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        Telefono.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 56, 112), 1, true), "Telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 3, 18), new java.awt.Color(238, 56, 112))); // NOI18N
        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });

        ContinuarButton.setBackground(new java.awt.Color(238, 56, 112));
        ContinuarButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ContinuarButton.setForeground(new java.awt.Color(255, 255, 255));
        ContinuarButton.setText("Continuar");
        ContinuarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegistroPanelLayout = new javax.swing.GroupLayout(RegistroPanel);
        RegistroPanel.setLayout(RegistroPanelLayout);
        RegistroPanelLayout.setHorizontalGroup(
            RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(TituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(123, 123, 123))
            .addGroup(RegistroPanelLayout.createSequentialGroup()
                .addGroup(RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(RegistroPanelLayout.createSequentialGroup()
                                .addComponent(UsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ContraseñaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ConfirmarContraTextField)
                            .addComponent(EmailTextField)
                            .addComponent(jSeparator1)
                            .addComponent(ApellidoPTextField)
                            .addComponent(NombreTextField)
                            .addComponent(ApellidoMTextField)
                            .addComponent(jSeparator2)
                            .addComponent(Telefono)))
                    .addGroup(RegistroPanelLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(ContinuarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegistroPanelLayout.setVerticalGroup(
            RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(TituloLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ApellidoPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ApellidoMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContraseñaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ConfirmarContraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ContinuarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FondoPanelLayout = new javax.swing.GroupLayout(FondoPanel);
        FondoPanel.setLayout(FondoPanelLayout);
        FondoPanelLayout.setHorizontalGroup(
            FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(RegistroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        FondoPanelLayout.setVerticalGroup(
            FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(RegistroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ApellidoPTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoPTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoPTextFieldActionPerformed

    private void ConfirmarContraTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarContraTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmarContraTextFieldActionPerformed

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void ContinuarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuarButtonActionPerformed
        
        String nombre = NombreTextField.getText();
        String apellidoP = ApellidoPTextField.getText();
        String apellidoM = ApellidoMTextField.getText();
        String tel = Telefono.getText();
        String email = EmailTextField.getText();
        String usuario = UsuarioTextField.getText();
        String contra = ContraseñaTextField.getText();
        String recontra = ConfirmarContraTextField.getText();
        
        if(nombre.isEmpty() || apellidoP.isEmpty() || apellidoM.isEmpty() || tel.isEmpty() || 
                email.isEmpty() || usuario.isEmpty() || contra.isEmpty() || recontra.isEmpty()){ 
            JOptionPane.showMessageDialog(null, "Rellena todos los campos, por favor.");
        }else{
            if(!contra.equals(recontra)){
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.");
            }else{
        
            long telefonoLong = Long.parseLong(tel);
        
            scp.registroPersona(nombre, apellidoP, apellidoM, telefonoLong, email, usuario, contra);
            this.dispose();
            frmRegistroT = new frmRegistroTarjeta(null, true, scp.getFolio());
            frmRegistroT.setVisible(true);
            }
        }
    }//GEN-LAST:event_ContinuarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmregistro dialog = new frmregistro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoMTextField;
    private javax.swing.JTextField ApellidoPTextField;
    private javax.swing.JTextField ConfirmarContraTextField;
    private javax.swing.JButton ContinuarButton;
    private javax.swing.JTextField ContraseñaTextField;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JPanel FondoPanel;
    private javax.swing.JTextField NombreTextField;
    private javax.swing.JPanel RegistroPanel;
    private javax.swing.JTextField Telefono;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JTextField UsuarioTextField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/LogoMP.jpg")));
    }
}
