/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

package Vista;
import Controlador.*;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Erick
 */
public class frmRegistroTarjeta extends javax.swing.JDialog {

    int userFolio;
    Suscripcion scp = new Suscripcion();
    
    public frmRegistroTarjeta(java.awt.Frame parent, boolean modal, int Folio) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setIconImage();
        this.userFolio = Folio;
    }
    
        public frmRegistroTarjeta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setIconImage();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanel = new javax.swing.JPanel();
        RegistroPanel = new javax.swing.JPanel();
        TituloLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        NoTarjetaField = new javax.swing.JTextField();
        FechaVencimientoField = new javax.swing.JTextField();
        CVVField = new javax.swing.JTextField();
        TipoTarComboBox = new javax.swing.JComboBox<>();
        RegistrarseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Moonligth Parking - Registro Tarjeta");

        FondoPanel.setBackground(new java.awt.Color(255, 255, 255));

        RegistroPanel.setBackground(new java.awt.Color(255, 255, 255));
        RegistroPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 56, 112), 4, true));

        TituloLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        TituloLabel.setForeground(new java.awt.Color(238, 56, 112));
        TituloLabel.setText("Datos de tarjeta");

        jSeparator1.setBackground(new java.awt.Color(238, 56, 112));
        jSeparator1.setForeground(new java.awt.Color(238, 56, 112));

        NoTarjetaField.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        NoTarjetaField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 56, 112), 1, true), "No. Tarjeta ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 3, 18), new java.awt.Color(238, 56, 112))); // NOI18N
        NoTarjetaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoTarjetaFieldActionPerformed(evt);
            }
        });

        FechaVencimientoField.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        FechaVencimientoField.setText("mm/aa");
        FechaVencimientoField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 56, 112), 1, true), "Fecha de vencimiento ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 3, 18), new java.awt.Color(238, 56, 112))); // NOI18N
        FechaVencimientoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaVencimientoFieldActionPerformed(evt);
            }
        });

        CVVField.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        CVVField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 56, 112), 1, true), "CVV", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 3, 18), new java.awt.Color(238, 56, 112))); // NOI18N
        CVVField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVVFieldActionPerformed(evt);
            }
        });

        TipoTarComboBox.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        TipoTarComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Credito", "Debito" }));
        TipoTarComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de tarjeta  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 2, 18))); // NOI18N
        TipoTarComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoTarComboBoxActionPerformed(evt);
            }
        });

        RegistrarseButton.setBackground(new java.awt.Color(238, 56, 112));
        RegistrarseButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        RegistrarseButton.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarseButton.setText("Registrarse");
        RegistrarseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegistroPanelLayout = new javax.swing.GroupLayout(RegistroPanel);
        RegistroPanel.setLayout(RegistroPanelLayout);
        RegistroPanelLayout.setHorizontalGroup(
            RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroPanelLayout.createSequentialGroup()
                .addGroup(RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistroPanelLayout.createSequentialGroup()
                                .addGroup(RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FechaVencimientoField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TipoTarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CVVField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegistrarseButton)))
                            .addComponent(NoTarjetaField, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RegistroPanelLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(TituloLabel)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        RegistroPanelLayout.setVerticalGroup(
            RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(TituloLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NoTarjetaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CVVField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaVencimientoField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(RegistroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TipoTarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistroPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(RegistrarseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout FondoPanelLayout = new javax.swing.GroupLayout(FondoPanel);
        FondoPanel.setLayout(FondoPanelLayout);
        FondoPanelLayout.setHorizontalGroup(
            FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(RegistroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        FondoPanelLayout.setVerticalGroup(
            FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(RegistroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NoTarjetaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoTarjetaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoTarjetaFieldActionPerformed

    private void FechaVencimientoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaVencimientoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaVencimientoFieldActionPerformed

    private void CVVFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVVFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CVVFieldActionPerformed

    private void TipoTarComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoTarComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoTarComboBoxActionPerformed

    private void RegistrarseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseButtonActionPerformed
        
        String numTarjetaTexto = NoTarjetaField.getText();
        String fechaVenc = FechaVencimientoField.getText();
        String cvvTexto = CVVField.getText();
        String tipoTarjeta = TipoTarComboBox.getSelectedItem().toString();
        
        if(numTarjetaTexto.isEmpty() || fechaVenc.isEmpty() || cvvTexto.isEmpty() || tipoTarjeta.isEmpty()){ 
            JOptionPane.showMessageDialog(null, "Rellena todos los campos, por favor.");
        }else{
            if(tipoTarjeta.equalsIgnoreCase("Seleccionar")){
                JOptionPane.showMessageDialog(null, "Selecciona un tipo de tarjeta.");
            }else{
                
                int numTarjeta = Integer.parseInt(numTarjetaTexto);
                int cvv = Integer.parseInt(cvvTexto);
                
                scp.registroTarjeta(this.userFolio, numTarjeta, tipoTarjeta, cvv, fechaVenc);
                
                scp.activaMembresia(this.userFolio);
                this.dispose();
            }
        }
    }//GEN-LAST:event_RegistrarseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistroTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistroTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistroTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistroTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmRegistroTarjeta dialog = new frmRegistroTarjeta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CVVField;
    private javax.swing.JTextField FechaVencimientoField;
    private javax.swing.JPanel FondoPanel;
    private javax.swing.JTextField NoTarjetaField;
    private javax.swing.JButton RegistrarseButton;
    private javax.swing.JPanel RegistroPanel;
    private javax.swing.JComboBox<String> TipoTarComboBox;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

        private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/LogoMP.jpg")));
    }
}
